apiVersion: v1
kind: ConfigMap
metadata:
  name: catering-services-config
  namespace: catering-dev
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  EUREKA_DEFAULT_ZONE: http://eureka-server:8761/eureka/