apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: catering-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: eureka-server:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: catering-dev
spec:
  selector:
    app: eureka-server
  ports:
    - name: http
      port: 8761
      targetPort: 8761