apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: catering-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/order_service?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catering-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: SPRING_DATA_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: catering-services-config
                  key: REDIS_HOST
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: catering-services-config
                  key: RABBITMQ_HOST
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: catering-secret
                  key: RABBITMQ_USERNAME
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catering-secret
                  key: RABBITMQ_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: catering-services-config
                  key: EUREKA_DEFAULT_ZONE
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_IP_ADDRESS
              value: "$(POD_IP)"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: order-service
            - name: EUREKA_INSTANCE_INSTANCE_ID
              value: "order-service:$(POD_IP):8083"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: catering-dev
spec:
  selector:
    app: order-service
  ports:
    - name: http
      port: 8083
      targetPort: 8083
